#!/bin/bash
# Detects the Mac's local Wi-Fi IP and writes it to LocalIP.xcconfig.
# Called as an Xcode "Run Script" build phase (before Compile Sources).
# Only runs for LOCAL_DEVICE builds; other configs skip silently.

if [ "$APP_ENV" != "LOCAL_DEVICE" ]; then
    exit 0
fi

OUTPUT="${SRCROOT}/ZomPart/SupportingFiles/Configs/LocalIP.xcconfig"

IP=$(ipconfig getifaddr en0 2>/dev/null)
if [ -z "$IP" ]; then
    IP=$(ipconfig getifaddr en1 2>/dev/null)
fi
if [ -z "$IP" ]; then
    echo "warning: Could not detect local IP. Using 127.0.0.1 as fallback."
    IP="127.0.0.1"
fi

echo "// Auto-generated by resolve-local-ip.sh — do not commit" > "$OUTPUT"
echo "SUPABASE_URL = ${IP}:54321" >> "$OUTPUT"

echo "Resolved local IP: ${IP}"
