#!/bin/bash
# Detects the Mac's local Wi-Fi IP and writes it to LocalIP.xcconfig.
# Called from the "ZomPart - Local Device" scheme as a Build Pre-action,
# and (defensively) also as a Run Script build phase.
# Only runs for LOCAL_DEVICE builds; other configs skip silently.
#
# Diagnostic messages use the `note:` / `warning:` prefixes that Xcode's
# structured logger picks up, so the resolved IP shows up in the build
# log under Pre-actions and in the Issue Navigator.

if [ "$APP_ENV" != "LOCAL_DEVICE" ]; then
    exit 0
fi

OUTPUT="${SRCROOT}/ZomPart/SupportingFiles/Configs/LocalIP.xcconfig"

# Try common Wi-Fi interfaces. On most Macs en0 is Wi-Fi, but on Macs with
# Thunderbolt-bridge or Ethernet adapters Wi-Fi sometimes shifts to en1/en2.
IP=""
for IFACE in en0 en1 en2 en3; do
    CANDIDATE=$(ipconfig getifaddr "$IFACE" 2>/dev/null)
    if [ -n "$CANDIDATE" ]; then
        IP="$CANDIDATE"
        IFACE_USED="$IFACE"
        break
    fi
done

if [ -z "$IP" ]; then
    echo "warning: [resolve-local-ip] Could not detect Wi-Fi IP on en0..en3. Falling back to 127.0.0.1 (device builds will fail to reach the host)."
    IP="127.0.0.1"
    IFACE_USED="loopback"
fi

echo "// Auto-generated by resolve-local-ip.sh — do not commit" > "$OUTPUT"
echo "SUPABASE_URL = ${IP}:54321" >> "$OUTPUT"

# `note:` makes the message appear in Xcode's build log and Issue Navigator.
# `warning:` would also surface it but draws more attention; use note for normal flow.
echo "note: [resolve-local-ip] Resolved local IP: ${IP} (interface ${IFACE_USED}) → ${OUTPUT}"
